- id: add-copyright-nkd
  name: Add NKD copyright header for new files
  description: Insert C/C++ style copyright header only for newly added files (git status A)
  entry: python3 check_copyright.py
  language: python
  files: \.(c|h|cpp|hpp|ino)$
  stages: [commit]
